/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


public class CompteurAvanceRecule extends javax.swing.JFrame {
    
    private final Timer timerPlusUn = new Timer(1000, this::timerPlusUnActionPerformed);
    private final Timer timerMoinsUn = new Timer(1000, this::timerMoinsUnActionPerformed);
   
    
    private enum Etat {
        E1, E2, E3;
    }
    
    private Etat etat;
    private int i;
    private int cpt;
    
    private void init() {
        etat = Etat.E1;
        initialiserEtat();
        initialiserCompteur();
    }
    
    private void initialiserEtat() {
        i = 0;
    }
    
    private void initialiserCompteur() {
        cpt = 0;
    }
    
    private void incrementerEtat() {
        i++;
    }
    
    private void incrementerCompteur (){
        cpt ++;
    }
    
    private void decrementerEtat() {
        i--;
    }
    
    private void decrementerCompteur (){
        cpt --;
    }
    
    private void afficherPouf() {
        jLabelTimer.setText("Pouf");
    }
    
    private void afficherCompteur() {
        jLabelTimer.setText(cpt+"");
    }
    
    private void transitionE1() {
        jButtonAvance.setEnabled(false);
        jButtonRecule.setEnabled(false);
        jButtonStop.setEnabled(false);
        jButtonStart.setEnabled(true);
        timerPlusUn.stop();
        timerMoinsUn.stop();
    }
    
    private void transitionE2() {
        jButtonAvance.setEnabled(false);
        jButtonRecule.setEnabled(true);
        jButtonStop.setEnabled(true);
        jButtonStart.setEnabled(false);
        timerMoinsUn.stop();
        timerPlusUn.start();
    }
    
    private void transitionE3() {
        jButtonAvance.setEnabled(true);
        jButtonRecule.setEnabled(false);
        jButtonStop.setEnabled(true);
        jButtonStart.setEnabled(false);
        timerMoinsUn.start();
        timerPlusUn.stop();
    }
    
    private void timerPlusUnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        switch (etat ) {
            case E1:
                //interdit
                break;
            case E2:
                incrementerCompteur();
                    incrementerEtat();
                    if (i > 3) {
                        afficherPouf();
                        etat = Etat.E1;
                        transitionE1();
                    } else {
                        afficherCompteur();
                    }
                break;
            case E3:
                //interdit
                break;
        }
        
                    
    }  
    
    private void timerMoinsUnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        switch (etat ) {
            case E1:
                //interdit
                break;
            case E2:
                //interdit
                break;
            case E3 :
                decrementerCompteur();
                decrementerEtat();
                if (i < 0) {
                    etat = Etat.E1;
                    transitionE1();
                } else {
                    afficherCompteur();
                }
                break;
        }
    }  
    /**
     * Creates new form CompteurSimple
     */
    public CompteurAvanceRecule() {
        initComponents();
        init();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGlobal = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jLabelTimer = new javax.swing.JLabel();
        jButtonAvance = new javax.swing.JButton();
        jButtonRecule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");
        jButtonStop.setEnabled(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jLabelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTimer.setText("0");

        jButtonAvance.setText("Avance");
        jButtonAvance.setEnabled(false);
        jButtonAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvanceActionPerformed(evt);
            }
        });

        jButtonRecule.setText("Recule");
        jButtonRecule.setEnabled(false);
        jButtonRecule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReculeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGlobalLayout = new javax.swing.GroupLayout(jPanelGlobal);
        jPanelGlobal.setLayout(jPanelGlobalLayout);
        jPanelGlobalLayout.setHorizontalGroup(
            jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelGlobalLayout.createSequentialGroup()
                        .addComponent(jButtonAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRecule, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStop, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelGlobalLayout.setVerticalGroup(
            jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlobalLayout.createSequentialGroup()
                .addComponent(jLabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAvance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGlobalLayout.createSequentialGroup()
                        .addGroup(jPanelGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGlobal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        switch(etat) {
            case E1 :
                    //interdit
                break;
            case E2 :
                    etat = Etat.E1;
                    transitionE1();
                    afficherPouf();
                break;
            case E3 :
                    etat = Etat.E1;
                    transitionE1();
                    afficherPouf();
                break;
        }
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        switch(etat) {
            case E1 :
                    etat = Etat.E2;
                    transitionE2();
                    initialiserEtat();
                    initialiserCompteur();
                    afficherCompteur();
                break;
            case E2 :
                    //interdit
                break;
            case E3 :
                    //interdit
                break;
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonReculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReculeActionPerformed
        switch(etat) {
            case E1 :
                    //interdit
                break;
            case E2 :
                    etat = Etat.E3;
                    transitionE3();
                break;
            case E3 :
                    //interdit
                break;
        }
    }//GEN-LAST:event_jButtonReculeActionPerformed

    private void jButtonAvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvanceActionPerformed
        switch(etat) {
            case E1 :
                    //interdit
                break;
            case E2 :
                    //interdit
                break;
            case E3 :
                    etat = Etat.E2;
                    transitionE2();
                break;
        }
    }//GEN-LAST:event_jButtonAvanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompteurAvanceRecule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompteurAvanceRecule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvance;
    private javax.swing.JButton jButtonRecule;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JPanel jPanelGlobal;
    // End of variables declaration//GEN-END:variables
}

