/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1;

import javax.swing.Timer;

public final class Exercice4 extends javax.swing.JFrame {

    public enum Etat {E1, E2, E3};
    private int i;
    public Etat etat;
    public int compteur;
    
    private final Timer timerPlusUn = new Timer(1000, this::timerPlusUnActionPerformed);
    private final Timer timerMoinsUn = new Timer(1000, this::timerMoinsUnActionPerformed);
    
    /**
     * Creates new form Exercice1
     */
    public Exercice4() {
        initComponents();
        etat = Etat.E1;
        PresentationE1();
        initialiserEtat();
        initialiserCompteur();
    }

    public void PresentationE1() {
        this.jButton1.setEnabled(true);
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        timerPlusUn.stop();
        timerMoinsUn.stop();
    }

    public void PresentationE2() {
        this.jButton1.setEnabled(false);
        this.jButton2.setEnabled(true);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(true);
        timerMoinsUn.stop();
        timerPlusUn.start();
    }
    
    public void PresentationE3() {
        this.jButton1.setEnabled(false);
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(true);
        this.jButton4.setEnabled(true);
        timerMoinsUn.start();
        timerPlusUn.stop();
    }
    
    
    private void initialiserEtat() {
        i = 0;
    }
    
    private void initialiserCompteur() {
        compteur = 0;
    }
    
    private void incrementerEtat() {
        i++;
    }
    
    private void incrementerCompteur (){
        compteur ++;
    }
    
    private void decrementerEtat() {
        i--;
    }
    
    private void decrementerCompteur (){
        compteur --;
    }
    
    private void afficherPouf() {
        jLabel1.setText("Pouf");
    }
    
    private void afficherCompteur() {
        jLabel1.setText(compteur+"");
    }
    
    private void timerPlusUnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        switch (etat ) {
            case E1:
                //interdit
                break;
            case E2:
                incrementerCompteur();
                incrementerEtat();
                afficherCompteur();
                break;
            case E3:
                //interdit
                break;
        }         
    }  
    
    private void timerMoinsUnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        switch (etat ) {
            case E1:
                //interdit
                break;
            case E2:
                //interdit
                break;
            case E3 :
                decrementerCompteur();
                decrementerEtat();
                if (i < 0) {
                    etat = Etat.E1;
                    PresentationE1();
                } else {
                    afficherCompteur();
                }
                break;
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("0");

        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // play
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(etat){
            case E1 :
                etat = Etat.E2;
                PresentationE2();
                initialiserEtat();
                initialiserCompteur();
                afficherCompteur();
                break;
            case E2 :
                break;
            case E3 :
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // décremente
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch(etat){
            case E1 :
                break;
            case E2 :
                etat = Etat.E3;
                PresentationE3();                
                break;
            case E3 :
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // incrémente
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        switch(etat){
            case E1 :
                break;
            case E2 :
                break;
            case E3 :
                etat = Etat.E2;
                PresentationE2();
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // stop
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        switch(etat){
            case E1 :
                break;
            case E2 :
                etat = Etat.E1;
                PresentationE1();
                afficherPouf();
                break;
            case E3 :
                etat = Etat.E1;
                PresentationE1();
                afficherPouf();
                break;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
