/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3;

import java.awt.Color;
import javax.swing.Timer;

/**
 *
 * @author uzanl
 */
public final class Exercice1 extends javax.swing.JFrame {

    private final Timer timerPanne = new Timer(1000, this::timerPanneActionPerformed);
    private final Timer timerEnMarche = new Timer(1000, this::timerEnMarcheActionPerformed);    
    public enum Etat {E1, E2, E3, E4, E5, E6};
    public Etat etat;
    public int compteur;
    
    /**
     * Creates new form Exercice1
     */
    public Exercice1() {
        initComponents();
        this.GreenLight.setCouleurOn(Color.GREEN);
        this.RedLight.setCouleurOn(Color.RED);
        this.OrangeLight.setCouleurOn(Color.ORANGE);
        etat = Etat.E6;
        presentationE6();
    }

    public void presentationE1() {
        this.GreenLight.allumer();
        this.RedLight.eteindre();
        this.OrangeLight.eteindre();
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(true);
    }

    public void presentationE2() {
        this.GreenLight.eteindre();
        this.RedLight.eteindre();
        this.OrangeLight.allumer();
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(true);
    }
    
    public void presentationE3() {
        this.GreenLight.eteindre();
        this.RedLight.allumer();
        this.OrangeLight.eteindre();
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(true);
        timerPanne.stop();
        timerEnMarche.start();
    }
    
    public void presentationE4() {
        this.GreenLight.eteindre();
        this.RedLight.eteindre();
        this.OrangeLight.eteindre();
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(false);
    }

    public void presentationE5() {
        this.GreenLight.eteindre();
        this.RedLight.eteindre();
        this.OrangeLight.allumer();
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(false);
        timerEnMarche.stop();
        timerPanne.start();
    }
    
    public void presentationE6() {
        this.GreenLight.eteindre();
        this.RedLight.eteindre();
        this.OrangeLight.eteindre();
        this.PlayButton.setEnabled(true);
        this.StopButton.setEnabled(false);
        this.PanneButton.setEnabled(false);
        timerPanne.stop();
        timerEnMarche.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StopButton = new javax.swing.JButton();
        PanneButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        OrangeLight = new tp3.Ampoule();
        RedLight = new tp3.Ampoule();
        GreenLight = new tp3.Ampoule();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        PanneButton.setText("Panne");
        PanneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneButtonActionPerformed(evt);
            }
        });

        PlayButton.setText("Play");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        OrangeLight.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout OrangeLightLayout = new javax.swing.GroupLayout(OrangeLight);
        OrangeLight.setLayout(OrangeLightLayout);
        OrangeLightLayout.setHorizontalGroup(
            OrangeLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        OrangeLightLayout.setVerticalGroup(
            OrangeLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        RedLight.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout RedLightLayout = new javax.swing.GroupLayout(RedLight);
        RedLight.setLayout(RedLightLayout);
        RedLightLayout.setHorizontalGroup(
            RedLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        RedLightLayout.setVerticalGroup(
            RedLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        GreenLight.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout GreenLightLayout = new javax.swing.GroupLayout(GreenLight);
        GreenLight.setLayout(GreenLightLayout);
        GreenLightLayout.setHorizontalGroup(
            GreenLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        GreenLightLayout.setVerticalGroup(
            GreenLightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrangeLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GreenLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RedLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RedLight, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(OrangeLight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GreenLight, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(PanneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timerEnMarcheActionPerformed(java.awt.event.ActionEvent evt) {                                         
        switch(etat){
            case E1 :
                etat = Etat.E2;
                presentationE2();
                break;
            case E2 :
                etat = Etat.E3;
                presentationE3();
                break;
            case E3 :
                etat = Etat.E1;
                presentationE1();
                break;
            case E4 :
                break;
            case E5 :
                break;
            case E6 :
                break;
        }
    } 

    private void timerPanneActionPerformed(java.awt.event.ActionEvent evt) {                                         
        switch(etat){
            case E1 :
                break;
            case E2 :
                break;
            case E3 :
                break;
            case E4 :
                etat = Etat.E5;
                presentationE5();
                break;
            case E5 :
                etat = Etat.E4;
                presentationE4();
                break;
            case E6 :
                break;
        }
    } 

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        switch(etat){
            case E1 :
                etat = Etat.E6;
                presentationE6();
                break;
            case E2 :
                etat = Etat.E6;
                presentationE6();
                break;
            case E3 :
                etat = Etat.E6;
                presentationE6();
                break;
            case E4 :
                etat = Etat.E6;
                presentationE6();
                break;
            case E5 :
                etat = Etat.E6;
                presentationE6();
                break;
            case E6 :
                break;
        }
    }//GEN-LAST:event_StopButtonActionPerformed

    private void PanneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneButtonActionPerformed
        switch(etat){
            case E1 :
                etat = Etat.E5;
                presentationE5();
                break;
            case E2 :
                etat = Etat.E5;
                presentationE5();
                break;
            case E3 :
                etat = Etat.E5;
                presentationE5();
                break;
            case E4 :
                break;
            case E5 :
                break;
            case E6 :
                break;
        }
    }//GEN-LAST:event_PanneButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        switch(etat){
            case E1 :
                break;
            case E2 :
                break;
            case E3 :
                break;
            case E4 :
                etat = Etat.E3;
                presentationE3();
                break;
            case E5 :
                etat = Etat.E3;
                presentationE3();
                break;
            case E6 :
                etat = Etat.E3;
                presentationE3();
                break;
        }
    }//GEN-LAST:event_PlayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tp3.Ampoule GreenLight;
    private tp3.Ampoule OrangeLight;
    private javax.swing.JButton PanneButton;
    private javax.swing.JButton PlayButton;
    private tp3.Ampoule RedLight;
    private javax.swing.JButton StopButton;
    // End of variables declaration//GEN-END:variables
}
