/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2;

import java.awt.Color;
import javax.swing.Timer;

/**
 *
 * @author uzanl
 */
public final class Exercice1 extends javax.swing.JFrame {

    private final Timer timerPanne = new Timer(1000, this::timerPanneActionPerformed);
    private final Timer timerEnMarche = new Timer(1000, this::timerEnMarcheActionPerformed);
   
    
    public enum Etat {E1, E2, E3, E4, E5, E6};
    public Etat etat;
    public int compteur;
    public Thread tinc;
    public Thread tdec;
    
    /**
     * Creates new form Exercice1
     */
    public Exercice1() {
        initComponents();
       /* this.GreenLight.setEnabled(false);
        this.RedLight.setEnabled(false);
        this.OrangeLight.setEnabled(false);*/
        etat = Etat.E6;
        PresentationE6();
    }

    public void PresentationE1() {
        this.GreenLight.setBackground(Color.GREEN);
        this.RedLight.setBackground(Color.WHITE);
        this.OrangeLight.setBackground(Color.WHITE);
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(true);
    }

    public void PresentationE2() {
        this.GreenLight.setBackground(Color.WHITE);
        this.RedLight.setBackground(Color.WHITE);
        this.OrangeLight.setBackground(Color.ORANGE);
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(true);
    }
    
    public void PresentationE3() {
        this.GreenLight.setBackground(Color.WHITE);
        this.RedLight.setBackground(Color.RED);
        this.OrangeLight.setBackground(Color.WHITE);
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(true);
        timerPanne.stop();
        timerEnMarche.start();
    }
    
    public void PresentationE4() {
        this.GreenLight.setBackground(Color.WHITE);
        this.RedLight.setBackground(Color.WHITE);
        this.OrangeLight.setBackground(Color.WHITE);
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(false);
    }

    public void PresentationE5() {
        this.GreenLight.setBackground(Color.WHITE);
        this.RedLight.setBackground(Color.WHITE);
        this.OrangeLight.setBackground(Color.ORANGE);
        this.PlayButton.setEnabled(false);
        this.StopButton.setEnabled(true);
        this.PanneButton.setEnabled(false);
        timerEnMarche.stop();
        timerPanne.start();
    }
    
    public void PresentationE6() {
        this.GreenLight.setBackground(Color.WHITE);
        this.RedLight.setBackground(Color.WHITE);
        this.OrangeLight.setBackground(Color.WHITE);
        this.PlayButton.setEnabled(true);
        this.StopButton.setEnabled(false);
        this.PanneButton.setEnabled(false);
        timerPanne.stop();
        timerEnMarche.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RedLight = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        PanneButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        OrangeLight = new javax.swing.JButton();
        GreenLight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RedLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedLightActionPerformed(evt);
            }
        });

        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        PanneButton.setText("Panne");
        PanneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneButtonActionPerformed(evt);
            }
        });

        PlayButton.setText("Play");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });

        OrangeLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrangeLightActionPerformed(evt);
            }
        });

        GreenLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenLightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrangeLight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RedLight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GreenLight, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StopButton)
                    .addComponent(PanneButton)
                    .addComponent(PlayButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RedLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrangeLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StopButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(GreenLight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timerEnMarcheActionPerformed(java.awt.event.ActionEvent evt) {                                         
        switch(etat){
            case E1 :
                etat = Etat.E2;
                PresentationE2();
                break;
            case E2 :
                etat = Etat.E3;
                PresentationE3();
                break;
            case E3 :
                etat = Etat.E1;
                PresentationE1();
                break;
            case E4 :
                break;
            case E5 :
                break;
            case E6 :
                break;
        }
    } 

    private void timerPanneActionPerformed(java.awt.event.ActionEvent evt) {                                         
        switch(etat){
            case E1 :
                break;
            case E2 :
                break;
            case E3 :
                break;
            case E4 :
                etat = Etat.E5;
                PresentationE5();
                break;
            case E5 :
                etat = Etat.E4;
                PresentationE4();
                break;
            case E6 :
                break;
        }
    } 

    private void RedLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedLightActionPerformed
   
    }//GEN-LAST:event_RedLightActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        switch(etat){
            case E1 :
                etat = Etat.E6;
                PresentationE6();
                break;
            case E2 :
                etat = Etat.E6;
                PresentationE6();
                break;
            case E3 :
                etat = Etat.E6;
                PresentationE6();
                break;
            case E4 :
                etat = Etat.E6;
                PresentationE6();
                break;
            case E5 :
                etat = Etat.E6;
                PresentationE6();
                break;
            case E6 :
                break;
        }
    }//GEN-LAST:event_StopButtonActionPerformed

    private void PanneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneButtonActionPerformed
        switch(etat){
            case E1 :
                etat = Etat.E5;
                PresentationE5();
                break;
            case E2 :
                etat = Etat.E5;
                PresentationE5();
                break;
            case E3 :
                etat = Etat.E5;
                PresentationE5();
                break;
            case E4 :
                break;
            case E5 :
                break;
            case E6 :
                break;
        }
    }//GEN-LAST:event_PanneButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        switch(etat){
            case E1 :
                break;
            case E2 :
                break;
            case E3 :
                break;
            case E4 :
                etat = Etat.E3;
                PresentationE3();
                break;
            case E5 :
                etat = Etat.E3;
                PresentationE3();
                break;
            case E6 :
                etat = Etat.E3;
                PresentationE3();
                break;
        }
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void OrangeLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrangeLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrangeLightActionPerformed

    private void GreenLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GreenLightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GreenLight;
    private javax.swing.JButton OrangeLight;
    private javax.swing.JButton PanneButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton RedLight;
    private javax.swing.JButton StopButton;
    // End of variables declaration//GEN-END:variables
}
