/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4.ex1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import tp4.Forme;

/**
 *
 * @author uzanl
 */
public class AireDeDessin extends javax.swing.JPanel {
    
    private final ArrayList<Forme> lignes = new ArrayList<>();
    
    BufferedImage mon_image;
    Graphics2D graphic;
    Point origin;
    int width;
    int height;
    Forme ligneEnCours;

    public AireDeDessin() {
        mon_image = null;
        origin = null;
    }

    public void setOrigin(Point p) {
        origin = p;
    }

    public void drawPreview(Point p) {
        ligneEnCours = new Forme(origin.x, origin.y, p.x, p.y, Forme.Type.Ligne);
        graphic.setPaint(Color.white);
        graphic.fillRect(p.x, p.y, 10, 10);
        repaint();
    }
    
    public void drawFinish(){
        lignes.add(this.ligneEnCours);        
        repaint();
    }
    

    

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
    
        Graphics2D drawable = (Graphics2D) g;

        // On reccupere quelques infos
        int width = getSize().width;
        int height = getSize().height;

        // on efface tout les dessins
        mon_image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        graphic = mon_image.createGraphics();
        graphic.setPaint(Color.white);
        graphic.fillRect(0, 0, width, height);
       
        graphic.setPaint(Color.RED);
        // on redessinne la ligne en cours de prévisualisation 
        if(ligneEnCours != null){
            graphic.drawLine(ligneEnCours.x1, ligneEnCours.y1, ligneEnCours.x2, ligneEnCours.y2);
        }
        
        graphic.setPaint(Color.black);
        // et toutes les lignes terminées
        if(lignes.size() > 0){
            for(Forme line : lignes) {
                graphic.drawLine(line.x1, line.y1, line.x2, line.y2);
            }
        }

        drawable.drawImage(mon_image, 0, 0, null);
    }
/*
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
